### ISSUE TITLE
Functions failing due to "error while loading shared libraries: libncurses.so.6"

### ISSUE THREAD

**Issue by corsair** [brefphp/extra-php-extensions#127]
As suggested by @mnapoli in [this issue](https://github.com/brefphp/bref/issues/803), it appears there may be some issue with an extension causing the following error to occur when a new function is started:

> /opt/bin/php: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory

This occurs even when starting with a fresh deployment via ``serverless deploy`` and ``serverless deploy --stage prod``, as well as on a new AWS account (to attempt to eliminate as many variables as possible).

My serverless.yml contains the following:
```yml
functions:
  worker:
    handler: worker.php
    layers:
      - ${bref:layer.php-80}
    events:
      -   sqs:
            arn:
              Fn::GetAtt: [ VehicleUpdateQueue, Arn ]
            # Only 1 item at a time to simplify error handling
            batchSize: 1

package:
  exclude:
    - .env
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
```

If it matters as well, I am on the following versions:
* bref/bref: 1.0.0
* bref/extra-php-extensions: 0.7.2
* bref/laravel-bridge: 1.0.0
* laravel/framework: 8.16.1
