### ISSUE TITLE
AWS Elasticache Extension

### ISSUE THREAD

**Issue by codybolinger** [brefphp/extra-php-extensions#165]
I am trying to create a custom AWS Elasticache Cluster Client extension using an AWS Lambda Layer but can't seem to get it working, per the instructions: https://bref.sh/docs/environment/php.html#custom-extensions

I'm not sure if I'm missing something crucial or the install steps for this extension are non-trivial, but any help is deeply appreciated and others might find this extension useful.

**Error**: 
`NOTICE: PHP message: PHP Warning: PHP Startup: Unable to load dynamic library '/opt/bref-extra/amazon-elasticache-cluster-client.so' (tried: /opt/bref-extra/amazon-elasticache-cluster-client.so (/opt/bref-extra/amazon-elasticache-cluster-client.so: cannot open shared object file: No such file or directory), /opt/bref/lib/php/extensions/no-debug-non-zts-20180731//opt/bref-extra/amazon-elasticache-cluster-client.so.so (/opt/bref/lib/php/extensions/no-debug-non-zts-20180731//opt/bref-extra/amazon-elasticache-cluster-client.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

**Elasticache Layer Dockerfile**:
```
FROM bref/build-php-73

RUN curl https://elasticache-downloads.s3.amazonaws.com/ClusterClient/PHP-7.3/latest-64bit | tar -C /tmp -zx

FROM public.ecr.aws/lambda/provided:al2

COPY --from=0 /tmp/amazon-elasticache-cluster-client.so /opt/bref-extra/amazon-elasticache-cluster-client.so
```

**custom php.ini**
`extension=/opt/bref-extra/amazon-elasticache-cluster-client.so`

**Serverless.yml**
```
provider:
  name: aws
  runtime: provided.al2
plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions
functions:
  index:
    handler: index.php
    layers:
      - ${bref:layer.php-73-fpm}
      - arn:aws:lambda:xx:yy:layer:elasticache:1
```

AWS installation instructions:
https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/Appendix.PHPAutoDiscoverySetup.Installing.html
