### ISSUE TITLE
`bref-extra:oci8-php-80` doesn't work

### ISSUE THREAD

**Issue by Benzoh** [brefphp/extra-php-extensions#323]
Hello. Let me ask you a question.
I think I've defined the extension correctly, but it doesn't work.

↓ serverless.yml
```
functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
            - ${bref-extra:oci8-php-80}
        events:
            - httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console" layer

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
```

![image](https://user-images.githubusercontent.com/13086429/153971908-7aa798a5-ffc1-4b3e-9757-75c5222ca759.png)

![image](https://user-images.githubusercontent.com/13086429/153971583-dd3104c3-a2fc-4988-8344-77419b30a42d.png)

![image](https://user-images.githubusercontent.com/13086429/153971516-a72ebc77-fadb-4cda-875f-f12008edeaf8.png)

Do I need to set anything else?
