### ISSUE TITLE
bref-extra:memcached not working?

### ISSUE THREAD

**Issue by itxp2008** [brefphp/extra-php-extensions#478]
Hi,

This is my serverless.yml

````
service: laravel

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # region: us-west-2
    # region: ap-northeast-1
    # Environment variables
    environment:
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-81-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-81-console
        # timeout: 720 # in seconds
        timeout: 90 # in seconds
        memorySize: 10240 #don't forget to change
        layers:
            - ${bref-extra:memcached-php-81}
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
````
   
In the deployed function layers it appears  

```
1 | php-81 | 54 | provided.al2 |
2 | console | 53 | provided.al2 |
3 | memcached-php-81 | 12 | provided |
```

Tested on both php8.1 and php8.2

1. Checked if the port 11211 is opened and it isn't.
2. Tried exec('memcached -V command')
3. The PHP Module is enabled
