### ISSUE TITLE
FFmpeg extension?

### ISSUE THREAD

**Issue by simocheccoli** [brefphp/extra-php-extensions#545]
Any plans for this extension?

**Comment by zmalter99** [comment]
This is how we use FFMPEG on PHP 8.5 . 

 `process-video.Dockerfile`
```
# This is Bref's "build" image that we can use to build custom binaries and extensions
FROM bref/build-php-85:3 AS build

# Install ffmpeg
RUN set -xe; \
    mkdir -p /tmp/ffmpeg; \
    curl -Ls https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz \
    | tar xJC /tmp/ffmpeg --strip-components=1
RUN mv /tmp/ffmpeg/ffmpeg /opt/bin/ffmpeg
RUN mv /tmp/ffmpeg/ffprobe /opt/bin/ffprobe

FROM bref/php-85:3
ENV BREF_RUNTIME=function

# Copy what we built above in our final image
COPY --from=build /opt /opt

 # Install extensions
COPY --from=bref/extra-imagick-php-85:3 /opt /opt

# Copy our source code in the image
COPY . /var/task

# Configure the handler file
CMD ["functions/process-video.php"]
```


`serverless.yml`
```
service: example

provider:
  name: aws
  region: us-east-1
  versionFunctions: false
  logRetentionInDays: 1
  ecr:
    images:
      process-video:
        path: .
        file: process-video.Dockerfile

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions

functions:
  process-video:
    description: 'Process video'
    timeout: 900
    memorySize: 10240
    maximumRetryAttempts: 0
    ephemeralStorageSize: 5120
    image:
      name: process-video
```
