### ISSUE TITLE
GD extension won't load

### ISSUE THREAD

**Issue by atymic** [brefphp/extra-php-extensions#588]
For some reason, seems the GD layer isn't loading correctly. Will investigate further

\/opt\/bref\/extensions\/gd.so: cannot open shared object file: No such file or directory

php config:
```ini
extension=intl
extension=gd
```

SLS file 
```yml
plugins:
    - serverless-lift
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions
provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # Environment variables

functions:

    # This function runs the Laravel website/API
    web:
        handler: Bref\LaravelBridge\Http\OctaneHandler
        runtime: php-84
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'
        environment:
            BREF_LOOP_MAX: 250
        layers:
            - ${bref-extra:gd-php-84}
```
